### ISSUE TITLE
Feature Request: Add SQLite as an option on Electron

### ISSUE THREAD

**Issue by stevenroussey-privicy** [jepiqueau/capacitor-data-storage-sqlite#10]

**Comment by jepiqueau** [comment]
Having a first look, it is not as easy as with electron when using sqlite3 module, one need to use electron-rebuild to build the native library which is platform ( MacOs, Windows,... ) dependent. So i returned the question to the capacitor development team to see how this is feasible.

**Comment by stevenroussey-desiclabs** [comment]
Thanks, having something cross platform would be great.

**Comment by jepiqueau** [comment]
@stevenroussey-privicy this is not yet implemented. This plugin is going to be deprecated visit @jeepq/capacitor for new releases. Can you re-open your issue over there thanks

**Comment by stevenroussey-privicy** [comment]
@jeepq/capacitor ? I don't see such a repo. Maybe misspelled?

**Comment by jepiqueau** [comment]
@stevenroussey-privicy  
look at ```https://github.com/jepiqueau/jeep/tree/master/capacitor/plugins-library``` 
to install it ```npm install --save @jeepq/capacitor@latest```
