### ISSUE TITLE
Creating a new Relational Database Model plugin that can be used as base for this.

### ISSUE THREAD

**Issue by fernandocode** [jepiqueau/capacitor-data-storage-sqlite#11]
I looked at issue #6 and I understand that this plugin should stay within scope. And really supporting Relational Database Model would be something outside of what the plugin proposes (Key/Value support).

So I would like to know the interest in creating a new plugin with the scope to support only Relational Database Model, which would support the execution of SQL statements, returning the cursor, with transaction support. Keeping within the scope of just being a proxy for native SQLite.
So it could even be used by other more specific plugins, including this one.

Currently in my projects I use relational model strongly in my databases, it is primordial for my type of application. I use cordova SQLite plugin (https://github.com/xpbrew/cordova-sqlite-storage), which has serious limitations on data flow between layers and transactions. In addition to being designed to be compatible with the WebSQL API that has been discontinued for some time and with cordova.

**Comment by jepiqueau** [comment]
i would like to share a new capacitor-sqlite plugin ```https://github.com/jepiqueau/capacitor-sqlite ``` and a ionic application demonstrating the use of  the capacitor-sqlite plugin  ```https://github.com/jepiqueau/ionic-capacitor-sqlite ``` This plugin is in alpha version and working for the time being for IOS, the Android version will come later. This plugin has been requested many time , please enjoy it and revert to me in case of issues as not all the SQL statements have been tested

**Comment by fernandocode** [comment]
What a great news. Unfortunately there is no Android implementation yet (I'm currently out of Mac to test), so once I have Android support I will test and possibly start [implementing an adapter](https://github.com/fernandocode/database-builder/tree/master/src/adapters) on [ionic-database-builder (library I developed for SQL abstraction, which I use in projects in the company and in some private projects)](https://github.com/fernandocode/database-builder).

Exellent initiative, I will look forward to the evolution of this library. @jepiqueau

**Comment by jepiqueau** [comment]
@fernandocode  the capacitor-sqlite plugin now includes both Native IOS and Android plugin. see https://github.com/jepiqueau/capacitor-sqlite
