### ISSUE TITLE
Demo Does Not Work in Firefox

### ISSUE THREAD

**Issue by Screech129** [jepiqueau/capacitor-data-storage-sqlite#12]
This demo: https://ionicpwacapacitorstorage.firebaseapp.com/ does not work in Firefox. I'm not sure if this is expected but it says "set: Error Data insertion failed: Error: No available storage method found."

**Comment by jepiqueau** [comment]
I got Firefox installed on my Mac version 67.0.4 (64 bit) and it works nicely. I also installed it on my Android mobile Version 68.2.0 and it failed. After some Google search, it seems that it is a known issue when using localforage to access INDEXEDDB, it sometimes does not find the driver. Whiv version of Firefox are you using and on which OS ?

**Comment by Screech129** [comment]
It's Firefox 70 on Windows 10. I attached a screenshot
![FirefoxScreenShot](https://user-images.githubusercontent.com/8851598/68306267-da793300-006e-11ea-815c-c8f80e5e98d9.png)

**Comment by jepiqueau** [comment]
@Screech129  This issue has been fixed, thanks for having reporting this bug
