### ISSUE TITLE
Feature request: Make the database name and table name parameters 

### ISSUE THREAD

**Issue by slevy85** [jepiqueau/capacitor-data-storage-sqlite#13]
Hi, thank you for this great plugin,
Do you think it is possible to have the database and table name as parameters somewhere ?

This would allow to have multiple db in the same application and separate different entities in different tables.

Thank you.

**Comment by jepiqueau** [comment]
These feature have been implemented

**Comment by jepiqueau** [comment]
@slevy85  Features implemented i will close the issue
