### ISSUE TITLE
For PWAs, "IDB" is appended to the end of the IndexedDB database name.

### ISSUE THREAD

**Issue by moose4lord** [jepiqueau/capacitor-data-storage-sqlite#21]
First of all, thank you for such a handy package to manage local storage. I'm thrilled it works on both mobile devices and PWAs. Just what I need to migrate from Cordova to Capacitor. But there's a catch:

My existing Ionic/Cordova app stores data in IndexedDB under a specific database name. Unfortunately, capacitor-data-storage-sqlite insists on appending "IDB" to the database name I pass to the openStore() function when run as a PWA. :(

openStore() function (in web.js):
```
let dbName = options.database ? `${options.database}IDB` : "storageIDB";
```
I would like to use the same database name in the Capacitor version of my app.

**Comment by jepiqueau** [comment]
@moose4lord Thanks for using the plugin. Yes, you right, i am appending IDB to the storage name for browser an SQLite.db for Native Platforms and Electron. This was done from the beginning and so difficult to modify as a number of people are using the plugin like this from the beginning. The best way for you is to rename the Cordova IDB database by adding IDB at the end. or to write a piece of code to run once to copy the Cordova IDB database to the plugin one. Sorry for this, hope you will understand.

**Comment by moose4lord** [comment]
I understand. I'll figure something out.

Thanks
