### ISSUE TITLE
I want to debug the sqlite db created by this plugin...

### ISSUE THREAD

**Issue by saas786** [jepiqueau/capacitor-data-storage-sqlite#22]
Hi @jepiqueau 

I am using your plugin, and I would like to debug / inspect the sqlite db I create using this plugin,

any suggestions, 

by default it doesn't seem to show up in chrome inspection tool.

I have found this reply:

https://stackoverflow.com/a/51350719

Which suggests Stetho by facebook, but not sure how to use it.

Also:

this article seems to make sense to me:

https://dzone.com/articles/ionic-how-to-access-or-browse-sqlite-database-byte

but I am not sure where db is located, so need to know the path, so I can follow the above tutorial?

this article suggests:

https://proandroiddev.com/android-sqlite-debug-tools-8b5e2d9a56b2

Stetho
SQLScout
AppSpector

but they are commercial solutions (apart from Stetho which I can seem to utilize).

Any suggestion which would allow me to debug db created with this plugin (without too much fuss) will be appreciated.

Ideally I would like to debug it realtime instead of copy pasting from device to pc and then browser etc.

Thanks

Note: I am able to locate the file using "Android Device File Explorer" and see it in SQLiteBrowser.

But I will appreciate if you have interactive debug / inspect solution, which allows me to see realtime data, manipulate it if needed.

**Comment by jepiqueau** [comment]
@saas786 On which platform are you using the plugin?
For Electron, Android and IOS which are SQLite database, i am using DB Browser for SQLite which is a free software. You copy the database from the device to a folder on your PC or Mac and you load it int DB Browser for SQLite
For Web browser using the Google Tools  Application folder, you will find the database in IndexDB

**Comment by saas786** [comment]
iOS & Android, correct I am able to do it like that, but I am looking for more interactive solution.

If I don't use your plugin, I can see the data stored in IDB via chrome inspector, and interact with it, which is how I would like to interact with database generated using your plugin (.sql file).

Any top of the head suggestions?

**Comment by jepiqueau** [comment]
@saas786 On Chrome if you look at more tools and development tools you go to the application folder and you will see the database  under IndexedDB the storageIDB database and under it the storage_store table and if you click on the table you will see on the right the key/value pair. If you have given a database and table names you will also see them under IndexDB databases.
