### ISSUE TITLE
sqlite?

### ISSUE THREAD

**Issue by zanethomas** [jepiqueau/capacitor-data-storage-sqlite#24]
This repo appears to have nothing to do with sqlite but instead is some sort of key/value layer? The name is confusing.

**Comment by jepiqueau** [comment]
@zanethomas first thanks for looking at the plugin. A bit surprised by your reaction. It has something to do with SQLLite. as mentioned in the README  
```
Capacitor Data Storage SQLite  Plugin is a custom Native Capacitor plugin to store permanently data to **SQLite** on IOS, Android and Electron platforms and to **IndexDB** for the Web platform.
Capacitor Data Storage SQLite Plugin provides a key-value store for simple data of **type string only** ...
```
So the plugin is doing what is said `Storing key-value pairs to a store` which is the meaning of the name of this plugin
Now, if you are looking to use SQLite for creating databases with table's schemas and data you should be looking at capacitor-sqlite which has been developed for that purpose.
Hope this will clarify
