### ISSUE TITLE
Error: connectionFailed: Unable to open a connection to database

### ISSUE THREAD

**Issue by codal-sbelim** [jepiqueau/capacitor-data-storage-sqlite#29]
I have designed my storage services as you suggested here.
https://github.com/jepiqueau/capacitor-data-storage-sqlite/issues/28#issuecomment-673904032

But unfortunately, I am getting a connection failed error after 120+ database queries.
Here is the detailed log of connection error I am facing. Any help would be appreciated.

`⚡️  To Native ->  CapacitorDataStorageSqlite get 34734185
connection: Unable to open a connection to database at /Users/Test/Library/Developer/CoreSimulator/Devices/776BBC68-3AE6-4C9C-9740-5E1CCDA4A37A/data/Containers/Data/Application/52A015BD-02E5-41A7-B3D3-92917FDF7518/Documents/ssw_storageSQLite.db
Error: connectionFailed
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/Test/Desktop/demo-ipad/node_modules/capacitor-data-storage-sqlite/ios/Plugin/Plugin.swift, line 116
2020-10-21 16:20:01.381898+0530 App[29206:594580] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/Test/Desktop/demo-ipad/node_modules/capacitor-data-storage-sqlite/ios/Plugin/Plugin.swift, line 116
(lldb) `

Following code, I am using for my DB connection.

```
async openStore1(
    dbName?: string,
    tableName?: string,
    isEncrypted?: boolean,
    encryptionMode?: string
  ): Promise<boolean> {
    try {
      let storeResult;
      const database: string = dbName ? dbName : 'app_storage';
      const table: string = tableName ? tableName : 'app_storage_table';
      const encrypted: boolean = isEncrypted ? isEncrypted : false;
      const mode: string = encryptionMode ? encryptionMode : 'no-encryption';
      if (storeResult && storeResult.result && storeResult.result === true) {
        storeResult = await this.store.setTable({ table });
      } else {
        storeResult = await this.store.openStore({
          database,
          table,
          encrypted,
          mode,
        });
      }
      return storeResult;
    } catch (e) {
      console.log('DB connection Error: ', e)
      return Promise.resolve(false);
    }
  }
```
Update data to the database

```
async setItem(key: string, value: string): Promise<void> {
    try {
      if (this.isService && key.length > 0) {
        
        if (this.storeResult && this.storeResult.result && this.storeResult.result === true) {
          await this.store.set({ key, value });
          return;
        } else {
          console.log('connection fail');
          return;
        }
      }
    } catch (e) {
      console.log('Error: ', e);
      return;
    }
  }
```

Plugin Config:

  ```
"dependencies": {
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@capacitor/android": "^2.1.0",
    "@capacitor/core": "2.1.0",
    "@capacitor/ios": "^2.1.0",
    "@ionic-native/core": "^5.26.0",
    "@ionic-native/file": "^5.27.0",
    "@ionic-native/file-opener": "^5.26.0",
    "@ionic-native/file-transfer": "^5.27.0",
    "@ionic-native/network": "^5.26.0",
    "@ionic-native/open-native-settings": "^5.28.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.1.1",
    "@ionic/pwa-elements": "^3.0.0",
    "capacitor-data-storage-sqlite": "^2.1.0",
    "cordova-open-native-settings": "^1.5.2",
    "cordova-plugin-network-information": "^2.0.2",
    "core-js": "^2.5.4",
    "ionic-selectable": "^4.5.0",
    "moment": "^2.27.0",
    "ng-openapi-gen": "^0.11.1",
    "prettier": "^2.0.5",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  }
```

**Comment by jepiqueau** [comment]
@codal-sbelim Which version of the plugin are you using ? Have you had a look to `https://github.com/jepiqueau/angular-data-storage-sqlite-app-starter` to write your service?

**Comment by codal-sbelim** [comment]
@jepiqueau I am using `"version": "2.1.0"`, and yes, I did took a reference from that repo and using that same store service. Just updated `openStore ` function a little bit as described in the previous comment to avoid multiple calls to open the database store.

**Comment by jepiqueau** [comment]
@codal-sbelim upgrade to capacitor-data-storage-sqlite@2.4.2-1 which is the latest release. I do not understand what you try to achieve the store is defined once when you call the first openStore command which is creating the store. After this the plugin is dealing with the connection to that store for each other commands and close the connection after processing them. So you do not have to do anything else. Hope this clarify

**Comment by codal-sbelim** [comment]
I stopped facing this issue after upgrading the plugin to `version 2.4.2-1` 
Thank you @jepiqueau
