### ISSUE TITLE
Need some pro tips to use in ReactJS

### ISSUE THREAD

**Issue by dhwalin** [jepiqueau/capacitor-data-storage-sqlite#30]
I have multiple components in multiple pages.

So do I need to open store everytime? Or openstore in App.tsx once and then just start setting items (setItem) by using setTable in different components of different pages?

I am beginner in ReactJS, so asking.

**Comment by jepiqueau** [comment]
@dhwalin Have you look at `https://github.com/jepiqueau/react-datastoragesqlite-app` ? this is an example app of how to use it. As on each page you import 
```
import { useStorageSQLite } from 'react-data-storage-sqlite-hook/dist';

``` 
and define `useStorageSQLite()` 
```
  const {openStore, getItem, setItem, getAllKeys, getAllValues,
    getAllKeysValues, isKey, setTable, removeItem, clear} = useStorageSQLite();

```

You the need to open the datastore for each page before using it. if you need to access a second store in the same page you run the command `openStore` on this second store and use any other commands to interact with that store. Then if you want in the same page to access again the first sore you run the command `openStore` on the first store and run any commands to interact with the first store and so forth... You can have only one store open at a time. Hope this will clarify

**Comment by dhwalin** [comment]
That's perfect. Thank you.

One more thing. In Readme.md (https://github.com/jepiqueau/capacitor-data-storage-sqlite/blob/master/readme.md)

public async getKeysValues(): Promise<Array<string>> {
    const { keysvalues } = await this.storage.keysvalues();
    return keysvalues;
  }

Get all keys-values is not explained. So if you can add, other user will get help directly.
