### ISSUE TITLE
JSON parse error: Unexpected identifier "data"

### ISSUE THREAD

**Issue by dhwalin** [jepiqueau/capacitor-data-storage-sqlite#32]
Platform iOS:

First I am opening database with getstarted table. Storing values in variable. Then setting the another table & trying to get its value. This time value is json stringify so converting to JSON.parse,

But returns the error: **JSON parse error: Unexpected identifier "data"**

```
let getSocialImages: boolean = await storage.openStore({database:"pfmaster",table:"getstarted"});
    
    if(getSocialImages){


      bgColor = await storage.getItem('CustomBGColor');
      fontColor = await storage.getItem('CustomFGColor');
      imageData = await storage.getItem('ownImageData');

      imageHeight = Number(await storage.getItem('ownImageHeight'));
  imageWidth = Number(await storage.getItem('ownImageWidth'));
  stageHeightVar = await imageHeight+305;

  
      

      let setProfileTable = await storage.setTable({table:"profiles"});

      if(setProfileTable[0]){

       
      const value_result:string = await storage.getItem(profileId);
      

        value_data = JSON.parse(value_result);
```

Please guide if I am missing something.

**Comment by jepiqueau** [comment]
@dhwalin it is difficult to answer without having the value for the key profileId.You should `console.log("value_result ", value_result)` to see what it is returned by the plugin.

**Comment by jepiqueau** [comment]
@dhwalin 
you could write
```
const value_result:string  = await storage.getItem(profileId);
if ( typeof(value_result) !== "undefined" && value_result !== null )  {
    value_data = JSON.parse(value_result);
} else {
    console.log("Error: value_result not returned");
}

**Comment by dhwalin** [comment]
I am receiving following values every-time. This seem something weird. Can "data" keyword in path make an issue? & the strange is, it doesn't give error in first attempt. 

If go back to page and repeat same process without refresh, it is occurring.

```
{"id":"profile_kgudb477","profileImg":"capacitor://localhost/_capacitor_file_/Users/dhwalin/Library/Developer/CoreSimulator/Devices/E93D421E-E845-xxxx/data/Containers/Data/Application/8842DC43-4ECF-xxx/Documents/pfimages/kgudap0n.jpeg","firstName":"dsds","lastName":"dvsdv","text1":"sdvsd","text2":"vsdv","text3":"","text4":"","fb":"sdv","ins":"ssv","tw":"","wa":""}
```

**Comment by dhwalin** [comment]
Sorry, it seems problem with my code. useEffect was causing issue. Thank you. This package is awesome.
