### ISSUE TITLE
Transpile the code to ES5 for older browsers

### ISSUE THREAD

**Issue by dimaip** [jepiqueau/capacitor-data-storage-sqlite#34]
**Describe the bug**
The code in the package is not transpilled e.g. it's using ES6 `class` construct.

**To Reproduce**
Run the code in older browsers e.g. IE11.

**Expected behavior**
The code should be transpiled to ES5 or at least a warning in big letters should be given at the top of the readme.

**Comment by jepiqueau** [comment]
@dimaip thank you for your comment, i did not test is on IE11 as i do not have it. Do you know an easy way to transpile it to ES5?

**Comment by dimaip** [comment]
@jepiqueau thanks for the reply!
Oh man, that's a complex topic. Basically you need to setup Babel to compile your source ES6 files to ES5 for you, which you'd trigger before making the release or automate it somehow.
But I guess it's also fine to not transpile it at all, just mention clearly in the readme that you'd need to transpile the code of this package in order to work in older browsers.

**Comment by jepiqueau** [comment]
@dimaip 
I discussed this through the capacitor contributors Slack channel. A doc will be issued some time on that subject as all the new Ionic Capacitor plugins are ES6 in the coming 3.0.0 release.
I will the follow your advice, put the following note in the README of each of my plugins:
`the plugin is ES6 compatible and cannot be used with ES5 apps without being transpiled`
Thanks for pointing out this to me. I have no idea on how many developers are still writing ES5 apps.

**Comment by dimaip** [comment]
Thanks!
I guess all devs who need IE11 support which I believe would still be the majority...

**Comment by jepiqueau** [comment]
@dimaip this has been added to the README file

```
## Browser Support

The plugin follows the guidelines from the `Capacitor Team`,

- [Capacitor Browser Support](https://capacitorjs.com/docs/v3/web#browser-support)

meaning that it will not work in IE11 without additional JavaScript transformations, e.g. with [Babel](https://babeljs.io/).

```
Hope this clarify. It has been added to all my plugins. Thank for pointing out that to me.
