### ISSUE TITLE
Deleting an specific Table

### ISSUE THREAD

**Issue by kzka90** [jepiqueau/capacitor-data-storage-sqlite#36]
How can I delete an specific table? If I pass the table name via the `deleteStore(options: capOpenStorageOptions)` on the `options` parameter, will it only delete that specific table? I don't want to delete the whole store.

**Comment by jepiqueau** [comment]
@kzka90 Thanks for using the plugin. There is no method implemented for this. deleteStore will delete the whole store. It is something which have to be added. May be when moving to capacitor 3.

**Comment by jepiqueau** [comment]
@kzka90 this has been added in release 3.0.0-alpha.6 (iOS & Android)
