### ISSUE TITLE
Error: CREATE TABLE statement could not be prepared (iOS)

### ISSUE THREAD

**Issue by kzka90** [jepiqueau/capacitor-data-storage-sqlite#37]
For some reason, it seems that I cannot `setTable` under iOS (Web works good. Haven't tried Android)

I keep getting the following error message:

```
⚡️  To Native ->  CapacitorDataStorageSqlite setTable 4875342
createTable: Error CREATE TABLE statement could not be prepared.
⚡️  TO JS {"result":false,"message":"setTable: failed in adding table"}
```

I'm trying to set the table like this:
`const { result, message } = await this.storage.setTable({table:"testing_table"});`

What could be causing this error?

I'm building over iOS 14.4.

**Comment by jepiqueau** [comment]
@kzka90 Thanks for using the plugin, i will have a look. I am currently quite busy with the move of @capacitor-community/sqlite to Capacitor3. So you have to be patient i will look at this when updating the plugin to Capacitor3 as it will require to go through all the code.

**Comment by jepiqueau** [comment]
@kzka90 this has been added in release 3.0.0-alpha.6 (iOS & Android)
