### ISSUE TITLE
Package update forecast

### ISSUE THREAD

**Issue by gerciljunio** [jepiqueau/capacitor-data-storage-sqlite#38]
I updated an application that I am developing for version 3 of the capacitor and due to an error of mine (very serious) I unfortunately had not seen that this package had not yet been updated. I know you are working on updating @ capacitor-community / sqlite but, do you have any idea (a prediction) when this package will be updated for capacitor 3?

**Comment by jepiqueau** [comment]
@gerciljunio hi, thanks for your request, it is on my TODO list, i am finalizing some fixes on the capacitor-video-player and after i will start the migration of the capacitor-data-storage-sqlite which may take some times to do. Hope in a meantime they will not be blocking issue on @capacitor-community/sqlite plugin. Which platform do you need at first if there is one?

**Comment by gerciljunio** [comment]
@jepiqueau sorry for the delay in responding, so I'm creating an application for Android and iOS, I would need for these two platforms, but if we choose one, it's Android! These days that I took a while to respond I was creating a simple alternative while your package is not updated which for now, will solve the problem temporarily! but i will keep an eye here and thank you very much for your packages! : D

**Comment by jepiqueau** [comment]
@gerciljunio i just start upgrading but i started with the iOS as i did not know what was your priority. The first release alpha.1 should not be used as it is just to help debugging and installing on the testing app. This is now my priority

**Comment by jepiqueau** [comment]
@gerciljunio both Android and iOS are now available.The Android part has been completely rewritten and based on `androidx.sqlite` the close of the store has been removed after each transaction for performance improvement. so a `close` method has been added this will be done on the iOS version soon. If you use it report any errors if any thanks

**Comment by gerciljunio** [comment]
@jepiqueau I'm starting to use the package and tests today, I'm going to inform you here, thank you very much!

**Comment by gerciljunio** [comment]
@jepiqueau all good? for now the package is working perfectly, I did not find any problem, but if something appears I will report here for you.

**Comment by jepiqueau** [comment]
@gerciljunio Thanks for the feedback and thanks for your contribution to testing. Do not hesitate if you find something.

**Comment by jepiqueau** [comment]
@gerciljunio Web & Electron parts of the plugin will come later

**Comment by jepiqueau** [comment]
@gerciljunio Everything is fix in 3.0.0. So i close the issue
