### ISSUE TITLE
Wrong parsing data in values array parameter in query function

### ISSUE THREAD

**Issue by Ahmedesayed** [jepiqueau/capacitor-data-storage-sqlite#39]
There is a problem in parsing data in query function , if you pass a number in values array it will be parsed as a string which will make a wrong query

**Comment by jepiqueau** [comment]
@Ahmedesayed  Which plugin are you talking about `capacitor-data-storage-sqlite` or `@capacitor-community-sqlite` . Can you provide your package.json file and the code part where the issue occurs
