### ISSUE TITLE
Import/Export feature

### ISSUE THREAD

**Issue by Gilmar-Gomes** [jepiqueau/capacitor-data-storage-sqlite#41]
First of all, congratulations and thanks for the brilliant work and contribution to the community!

I have projects that use the library and benefit from all its resources. However, it would be extremely useful if there were methods to import / export (dump) a datastore in json format for purposes like backup and packaging for data synchronization. What would be the possibility of supporting this in an upcoming release?

**Comment by jepiqueau** [comment]
@Gilmar-Gomes Thanks for using the plugin and make proposal for improvements. I will have a look at this when i will have completed the upgrade of my 4 plugins to Capacitor 3 . Hope you can wait till there.

**Comment by jepiqueau** [comment]
@Gilmar-Gomes Thank for your patience. this enhancement has been fixed in version 3.2.0 of the plugin

**Comment by jepiqueau** [comment]
@Gilmar-Gomes When you will have test it. Please close the issue

**Comment by Gilmar-Gomes** [comment]
Ohh sure! thanks! I've tested it and works like a charm!
