### ISSUE TITLE
Capacitor 3 Upgrade and single quotes in data make sqlite inserts fail.

### ISSUE THREAD

**Issue by triviware** [jepiqueau/capacitor-data-storage-sqlite#45]
First of all, i consider this a bug because on the previous version (before Capacitor 3), i had not problem with my data.

ONLY AFFECTS ANDROID. BROWSER AND IOS works fine.

When you try to save some string that contains single quotes (not escaped), plugin fails. Besides, the error says that plugin doesn't work on Android, which is not true.

I had this issue on a Ionic/Angular app, tested on a ZTE Blade Smart 10 with Android 9. I used Android Studio 4.1 and Gradle 7.0.

If you need more info, tell me.

Thank you for your work!!

**Comment by jepiqueau** [comment]
@triviware thank you for using the plug-in can you share an example of data which fails so I can reproduce the error. I am still travelling so I will look at it in 2 days from now. Hope you can wait till there

**Comment by jepiqueau** [comment]
@triviware This has been fixed in 3.0.2 Thanks for helping in the debugging process.

**Comment by triviware** [comment]
@jepiqueau Yes, it works now! Thank you and sorry, you were faster solving this than me giving you an example!

**Comment by jepiqueau** [comment]
@triviware you are welcome. So I close the issue
