### ISSUE TITLE
Debug logs in distribution build

### ISSUE THREAD

**Issue by flipace** [jepiqueau/capacitor-data-storage-sqlite#48]
**Describe the bug**
Various debug `console.log`s are in the distribution build.

Maybe it would make sense to switch to e.g. the [debug](https://www.npmjs.com/package/debug) package instead for such things?

**To Reproduce**
Just use the plugin in the web version, and you'll see the `console.log` output, eg from here: https://github.com/jepiqueau/capacitor-data-storage-sqlite/blob/7965804c40a3c363f66b81c947380d6c62823e17/dist/esm/web.js#L15

**Expected behavior**
Debug logs should not appear in production/distribution builds of the plugin.

**Comment by jepiqueau** [comment]
@flipace You right i will remove them in the next release

**Comment by jepiqueau** [comment]
@flipace fix in release 3.1.2-3. Fill free to close it when tested
