### ISSUE TITLE
Specify database sqlite file location when creating a store

### ISSUE THREAD

**Issue by garbit** [jepiqueau/capacitor-data-storage-sqlite#50]
**Is your feature request related to a problem? Please describe.**
When initializing the sqlite store I'd like to be able to specfiy where I'd like the resulting ```.db``` file will be stored on my disk (iOS + Android).

**Describe the solution you'd like**
As part of the ```capOpenStorageOptions``` I'd like to be able to specify ```path``` to assign a database file path when initializing the store.

By specifying the path my ```.db``` file would be stored under that location e.g. ```/MY_DIRECTORY_PATH_HERE/my_database.db```

Something like the following:
```
import { CapacitorDataStorageSqlite, capOpenStorageOptions} from "capacitor-data-storage-sqlite";

async function openStore(dbName, table) {
    const options: capOpenStorageOptions = {
      path: 'MY_DIRECTORY_PATH_HERE'
      database: dbName,
      table: table
    }
    const sqlStore = CapacitorDataStorageSqlite
    await sqlStore.openStore(options)
    ...
}
```

**Describe alternatives you've considered**
I don't believe it's currently possible to specify where the store is located. Therefore my database files are located in the root directory of my app on iOS.

Thanks in advance for your consideration.

**Comment by jepiqueau** [comment]
@garbit Is it for the Electron plug-in or for the native plug-ins. I do not really understand the reason for adding that complexity to the plug-in.  No one has ask for since the launch of the plug-in. Can you elaborate on the reasons behind this query?

**Comment by garbit** [comment]
Hi @jepiqueau I'm using the native plug-ins (iOS specifically) so that I can logically structure my local files. I'm creating an app where the user can load files into the system by dropping them into a specific folder. However, with the .db files in the root folder they might be easily deleted by a novice user when altering the folder structure.

**Comment by jepiqueau** [comment]
@garbit I understand but i am not sure i will do this. Where the /MY_DIRECTORY_PATH_HERE will be residing under Documents, Applications, Library ... ?

**Comment by garbit** [comment]
This seems to be out of scope of the project at the moment. Closing the issue.
