### ISSUE TITLE
Can this plugin be used as a driver for Ionic Storage?

### ISSUE THREAD

**Issue by mariusbolik** [jepiqueau/capacitor-data-storage-sqlite#54]
First of all: Thank you for the good work!
Can this plugin be used as a driver for Ionic Storage like CordovaSQLiteDriver? 
https://github.com/ionic-team/ionic-storage#sqlite-installation

Regards,
Marius

**Comment by jepiqueau** [comment]
@mariusbolik i do not have any ideay

**Comment by mariusbolik** [comment]
No. Is there no Driver for Ionic Storage?

**Comment by jepiqueau** [comment]
@mariusbolik I think you have to select one or the other. the capacitor-data-storage-sqlite has been developed when the ionic team push capacitor as a first trial of developing a capacitor plugin at that time the Ionic Storage was not there as it is today. Now it seems that they support also SQLite for native app. so it is up to you. Please close this issue,

**Comment by mburger81** [comment]
@jepiqueau what do you mean with "Now it seems that they support also SQLite for native app, so it is up to you"

thx for your work

**Comment by jepiqueau** [comment]
@mburger81 i did not look in detail and it was last may so i forgot about it sorry for this.

**Comment by mburger81** [comment]
@jepiqueau @mariusbolik  I wrote a driver for `localforage`, this driver gives you the possibility to use the lib as localforage driver in IonicStorage or on state management tools like Akita.

I would like to share with you the driver, maybe you could add it to the capacitor plugin itself so everybody can use it.

**Comment by jepiqueau** [comment]
@mariusbolik why not i could have a look or may be you do a PR to put it inside the plugin

**Comment by mariusbolik** [comment]
> @jepiqueau @mariusbolik I wrote a driver for `localforage`, this driver gives you the possibility to use the lib as localforage driver in IonicStorage or on state management tools like Akita.
> 
> I would like to share with you the driver, maybe you could add it to the capacitor plugin itself so everybody can use it.

Sounds great! A PR would be appreciated!

**Comment by jepiqueau** [comment]
@mburger81 Are you making a PR out of your driver ?

**Comment by jepiqueau** [comment]
@mburger81 any progress on this PR

**Comment by mariusbolik** [comment]
@mburger81 Could you please create a PR on this repo, so the community can use your driver? :)

**Comment by mj2068** [comment]
@mburger81 it would be very appreciated if you could share the driver.

**Comment by mburger81** [comment]
Sorry I saw this just now! I'll for sure share my driver in a few days!

**Comment by marcelkipp** [comment]
Picking up on this since I am facing the same issue of needing to use the plugin as driver for Ionic Storage.
Was this ever merged and if yes, how can I use the driver? My setup look similar to the mentioned by @mburger81 in [this closed issue](https://github.com/capacitor-community/sqlite/issues/318)

Maybe you can give an example as I do not see anything in the docs gerading this.
