### ISSUE TITLE
Unhandled Rejection: CapacitorDataStorageSqlite plugin is not implemented on Android

### ISSUE THREAD

**Issue by Franjoo** [jepiqueau/capacitor-data-storage-sqlite#64]
**Describe the bug**
App throws "Unhandled Rejection: CapacitorDataStorageSqlite plugin is not implemented on Android"

**Environment**
- "react": "^17.0.2",
- "@capacitor/core": "4.6.2",
- "@capacitor/android": "4.6.2"
- "capacitor-data-storage-sqlite": "^4.0.1",
- gradle v7.4.2
- gradle plugin v7.3.1

**What I tried**
- ./gradlew --stop
- rm -r $HOME/.gradle/caches
- rm -r .gradle/caches (local caches if present)
- Clean Project (Android Studio)
- Sync Project with Gradle Files (Android Studio)
- delete application cache, delete application data, delete whole application -> fresh application install

- [https://github.com/jepiqueau/capacitor-data-storage-sqlite/issues/40](https://github.com/jepiqueau/capacitor-data-storage-sqlite/issues/40) -> did not help
- [https://github.com/capacitor-community/sqlite/issues/134#issuecomment-862421988](https://github.com/capacitor-community/sqlite/issues/134#issuecomment-862421988) -> did not help

**Comment by jepiqueau** [comment]
@Franjoo can you try gradle plugin 7.2.2 if it does not work you will have to create a small app reproducing the issue and share it on github.

**Comment by jepiqueau** [comment]
@Franjoo Is it solve? if yes please close the issue

**Comment by Franjoo** [comment]
Sorry for the late response. The project is not in scope anymore, therefore I can't test it :/
