### ISSUE TITLE
SQLite with capacitor + Ionic 4 app

### ISSUE THREAD

**Issue by Madhulika08** [jepiqueau/capacitor-data-storage-sqlite#7]
Hi,

I am trying to migrate from Cordova to the capacitor. In our app, we use SQL queries to save and get data and perform other actions on the database. Not sure how to do it using this plugin.
Do we have an example or do we have any other plugin in capacitor which supports this requirement?

**Comment by jepiqueau** [comment]
see an example of ionic app   
``` 
https://github.com/jepiqueau/ionic-capacitor-data-storage-sqlite 
``` 
you cannot perform others operations that the one given in the readme files  
``` 
clear()                             clear the store
get({key:"foo"})                    get a value given the key           
iskey({key:"foo"})                  test key exists
keys()                              get all keys
keysvalues()                        get all key/value pairs
remove({key:"foo"})                 remove a key
set({key:"foo",value:"foovalue"})   set key and its value
values()                            get all values 
```
the database is stored and have a unique name and table.
So if you are looking to create your own database model  see my answer to 
```  
https://github.com/jepiqueau/capacitor-data-storage-sqlite/issues/6
```

**Comment by parthnayak7448** [comment]
@Madhulika08  Did you find any solutions to use sql query in capacitor? If yes can you share me example please.

**Comment by jepiqueau** [comment]
hi all i would like to share a new capacitor-sqlite plugin https://github.com/jepiqueau/capacitor-sqlite and a ionic application demonstrating the use of the capacitor-sqlite plugin https://github.com/jepiqueau/ionic-capacitor-sqlite This plugin is in alpha version and working for the time being for IOS, the Android version will come later. This plugin has been requested many time , please enjoy it and revert to me in case of issues as not all the SQL statements have been tested

**Comment by jepiqueau** [comment]
@Madhulika08 , @parthnayak7448 see my comment above

**Comment by vasiliyevgrashin71** [comment]
capacitor-data-storage-sqlite not working ;(

**Comment by jepiqueau** [comment]
@vasiliyevgrashin71 You should be more specific which OS (Mac, Window, iOS, Android, Electron)? which Platform (iOS, Android, Electron, Web ) ? which Browser (Chrome, Safari, Firefox) ? ... ?
i tested on Android, IOS, Electron and web the application ```ionic-capacitor-data-storage-sqlite``` at https://github.com/jepiqueau/ionic-capacitor-data-storage-sqlite using the latest release of the capacitor-data-storage-sqlite 1.2.1-10 and it works fine. i tested also the capacitor-data-storage-sqlite viewme and it also works fine.

**Comment by carloliwanag** [comment]
@jepiqueau great plugin. it is very easy to use and your documentation is enough to have used in applications. thanks! 

I am currently using it in my android application using ionic 4 and it is working great. I just noticed that it still uses indexeddb when I open the dev tools (remote devices). Is there a config that I need to do so that it uses sqlite db? Thanks.

**Comment by jepiqueau** [comment]
@carloliwanag  make sure to define the plugin in the MainActivity
```import com.jeep.plugin.capacitor.CapacitorDataStorageSqlite;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
      add(CapacitorDataStorageSqlite.class);
    }});
  }
}
``` and it should work

**Comment by jepiqueau** [comment]
@carloliwanag  sorry i also forgot you should make an import
```import com.jeep.plugin.capacitor.CapacitorDataStorageSqlite; ```

**Comment by Trenacia** [comment]
Hello, why add these two lines to this file ?

I don't have them and it works very well.

**Comment by jepiqueau** [comment]
@Trenacia 
That is not possible without these two line in the MainActivity of your App in Android only. So basically it works but you are using the storage with the web browser and not  to sqlite database.
