### ISSUE TITLE
Use with swift 4

### ISSUE THREAD

**Issue by atmosuwiryo** [jepiqueau/capacitor-data-storage-sqlite#8]
Can we use this plugin with swift version 4?

**Comment by jepiqueau** [comment]
if your question is in a pure IOS swift4 app, the answer is no as it is a capacitor plugin meaning that its interface is compliant to  capacitor. Now what you can do in a pure Swift app is to take the StorageDatabaseHelper.swift class from https://github.com/jepiqueau/capacitor-data-storage-sqlite/blob/master/ios/Plugin/Plugin/StorageDatabaseHelper.swift and add it to your swift app. you must also add the dependency SQLite.swift as wrapper for SQLite and this should work. it is in fact the way i use it to test it purely as an IOS app before to interface it for capacitor. Hope this will help

**Comment by jepiqueau** [comment]
have you create your ionic project following the instruction given in ```https://capacitor.ionicframework.com/docs/getting-started/with-ionic/ ``` 
Did you look at the Ionic4 app at 
``` https://github.com/jepiqueau/ionic-capacitor-data-storage-sqlite ```
which is using the plugin without issues. can you tell me which ionic version are you using and which capacitor version. Are you opening Ios with 
``` npx cap open ios ``` 
and clean then project and build the project.
Can you share the ``` package.json ``` file of your ionic project  or even have your project on github so i can clone it and have a look

**Comment by atmosuwiryo** [comment]
I'm sorry, I only can check this next week. I'll back to you after that.
