### ISSUE TITLE
"No available storage method found" error caused by INDEXEDDB on iOS web devices

### ISSUE THREAD

**Issue by Genericum** [jepiqueau/capacitor-data-storage-sqlite#9]
### Version:
capacitor-data-storage-sqlite version: 1.2.1

###  Type:
I'm submitting a ...

[x] bug report
[] feature request

### Current behavior:
The ionic-capacitor-data-storage-sqlite app example does not work in chrome, if an iOS device is selected in development mode. On Safari for Mac OS the ionic-capacitor-data-storage-sqlite app does also not work if an iOS device is selected in responsive mode.

![sql_error](https://user-images.githubusercontent.com/27863084/64716332-7b5dce80-d4c2-11e9-850e-9f5b5dae67ce.jpg)

### Expected behavior:
The store works on iOS devices in web mode.

### Steps to reproduce:
* git clone https://github.com/jepiqueau/ionic-capacitor-data-storage-sqlite.git ionic-capacitor-data-storage-sqlite
* cd ionic-capacitor-data-storage-sqlite
* git remote rm origin
* npm install
* ng serve
* Open Chrome and start dev tools
* Select an iOS device - for example "iPhone 6/7/8"
* Run the test by clicking "Test Plugin"

### Important notice:
If i change the config in StorageDatabaseHelper.js from _driver: LocalForage.INDEXEDDB_ to _driver: LocalForage.WEBSQL_ in the directory node_modules, everything works fine. 

Thank you for your support and the great capacitor-data-storage-sqlite.

**Comment by jepiqueau** [comment]
i am back, i identified the issue which is coming from localforage module which do not recognize that Safari version is higher that 10.1 and so LocalForage.INDEXEDDB driver is not recognized and it fall back to LocalForage.WEBSQL if an IOS device is selected in Chrome in development mode.
For me, On Safari for Mac OS the ionic-capacitor-data-storage-sqlite app does work if an iOS device is selected in responsive mode. i am running Safari 13.0.1

**Comment by jepiqueau** [comment]
this issue has been fixed in version 1.2.1-4
